### ISSUE TITLE
On Station 3.1

### ISSUE THREAD

**Issue by ncave** [ncave/OnStation#1]
Hello @Tacovan,

I've uploaded an old copy of your On Station 3.1 here, just so it doesn't get lost in the sands of time, as people around the world are still using it, believe it or not. Please let me know if you're not OK with that and I'll take it down. Please also consider forking it, then I can delete this copy.

There is another copy on GitHub but this one is migrated to VS2017 and works correctly (if compiled for 32-bit) on Windows 10. It still runs perfectly fine after all those years, I just had to make a minor change to the labels background color to fix it.

**Comment by Tacovan** [comment]
Hey, that's totally fine. Thank you. Glad to see it still being used :-)

Taco

**Comment by ncave** [comment]
@Tacovan Thanks for writing it!
If you decide to fork it, I can delete this one so your fork goes on top. Have a great day!
